### ISSUE TITLE
netapp_elementsw_module.py: get_snapshot() cannot gracefully handle non-existing snapshot id's

### ISSUE THREAD

**Issue by scaleoutsean** [ansible-collections/netapp#65] opened 2020-10-15 15:08 UTC
##### SUMMARY

get_snapshot() crashes on snapshot id var that does not exist, causing tasks to fail mid-way, in a non-graceful manner

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

- `plugins/module_utils/netapp_elementsw_module.py` get_snapshot() function

##### ANSIBLE VERSION

```paste below
ansible 2.10.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/sean/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/sean/.local/lib/python3.6/site-packages/ansible
  executable location = /home/sean/.local/bin/ansible
  python version = 3.6.9 (default, Jul 17 2020, 12:50:27) [GCC 8.4.0]
```

##### CONFIGURATION

```paste below
DEFAULT_DEBUG(env: ANSIBLE_DEBUG) = True
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = explicit
DEFAULT_LOG_PATH(env: ANSIBLE_LOG_PATH) = /home/sean/.ansible/collections/ansible_collections/netapp/elementsw/ansible.log
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = ['/etc/ansible/content']
DEFAULT_STDOUT_CALLBACK(env: ANSIBLE_STDOUT_CALLBACK) = debug
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(env: ANSIBLE_PYTHON_INTERPRETER) = /usr/bin/python3
```

##### OS / ENVIRONMENT

- Ubuntu 18
- SolidFire 12
- Latest NetApp / ElementSW modules

##### STEPS TO REPRODUCE

- Pick existing and correct values for everything except `src_snapshot_id` (use a snapshot id that does not exist - in my environment for example `15330` does not exist): 

```yaml
tasks:
    - name: Copy SF Volume
      na_elementsw_volume_clone:
        hostname: "{{ sf_hostname }}"
        username: "{{ sf_username }}"
        password: "{{ sf_password }}"
        src_volume_id: "{{ sf_vol_id }}"
        src_snapshot_id: "{{ sf_snap_id }}"
        account_id: 9
        name: test2
      register: result
```

##### EXPECTED RESULTS

`get_snapshot()` handles the API error and returns `None`. Or fail immediately (in netapp_elementsw_module.py) since we already know this task won't complete:

```
[WARNING]: The value "21" (type int) was converted to "'21'" (type string). If this does not look like what you expect,
quote the entire value to ensure it does not change.
[WARNING]: The value "15330" (type int) was converted to "'15330'" (type string). If this does not look like what you
expect, quote the entire value to ensure it does not change.
[WARNING]: The value "9" (type int) was converted to "'9'" (type string). If this does not look like what you expect,
quote the entire value to ensure it does not change.
fatal: [192.168.1.34]: FAILED! => {
    "changed": false
}

MSG:

Snapshot id not found: 15330
```

##### ACTUAL RESULTS

- get_snapshots() can't handle non-existing snapshot id's:

```paste below
2020-10-15 22:23:07,252 - solidfire.Element - INFO - {"method": "ListSnapshots", "id": 4, "params": {"volumeID": 21, "snapshotID": "15330"}}
Traceback (most recent call last):
  File "/home/sean/.ansible/tmp/ansible-tmp-1602771785.9104586-2590-94545454477935/AnsiballZ_na_elementsw_volume_clone.py", line 102, in <module>
    _ansiballz_main()
  File "/home/sean/.ansible/tmp/ansible-tmp-1602771785.9104586-2590-94545454477935/AnsiballZ_na_elementsw_volume_clone.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/sean/.ansible/tmp/ansible-tmp-1602771785.9104586-2590-94545454477935/AnsiballZ_na_elementsw_volume_clone.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.netapp.elementsw.plugins.modules.na_elementsw_volume_clone', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_na_elementsw_volume_clone_payload_1x1ajsh3/ansible_na_elementsw_volume_clone_payload.zip/ansible_collections/netapp/elementsw/plugins/modules/na_elementsw_volume_clone.py", line 276, in <module>
  File "/tmp/ansible_na_elementsw_volume_clone_payload_1x1ajsh3/ansible_na_elementsw_volume_clone_payload.zip/ansible_collections/netapp/elementsw/plugins/modules/na_elementsw_volume_clone.py", line 272, in main
  File "/tmp/ansible_na_elementsw_volume_clone_payload_1x1ajsh3/ansible_na_elementsw_volume_clone_payload.zip/ansible_collections/netapp/elementsw/plugins/modules/na_elementsw_volume_clone.py", line 252, in apply
  File "/tmp/ansible_na_elementsw_volume_clone_payload_1x1ajsh3/ansible_na_elementsw_volume_clone_payload.zip/ansible_collections/netapp/elementsw/plugins/modules/na_elementsw_volume_clone.py", line 201, in get_snapshot_id
  File "/tmp/ansible_na_elementsw_volume_clone_payload_1x1ajsh3/ansible_na_elementsw_volume_clone_payload.zip/ansible_collections/netapp/elementsw/plugins/module_utils/netapp_elementsw_module.py", line 137, in get_snapshot
  File "/home/sean/.local/lib/python3.6/site-packages/solidfire/__init__.py", line 3540, in list_snapshots
    since=6.0
  File "/home/sean/.local/lib/python3.6/site-packages/solidfire/common/__init__.py", line 704, in send_request
    response["error"]["message"])
solidfire.common.ApiServerError: ApiServerError(method_name="ListSnapshots", err_json=500 xSnapshotIDDoesNotExist Snapshot 15330 does not exist.)
```

**Comment by lonico** [comment] 2020-10-28 18:55
I'm not able to reproduce the issue.
I'm seeing
```
TASK [Copy SF Volume] ***************************************************************************************************************************************************************************************************************************************************
[WARNING]: The value "hostname: 15330" (type int) was converted to "hostname: '15330'" (type string). If this does not look like what you expect, quote the entire value to ensure it does not change.
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Snapshot id not found: 15330"}
```

You are using colection, but there is something suspicious in
```
ansible_collections/netapp/elementsw/plugins/module_utils/netapp_elementsw_module.py", line 137,
```
The line number does not match what we released.

**Comment by scaleoutsean** [comment] 2020-10-29 04:42
I'll have to recheck this in a fresh VM-based install. As I went on with troubleshooting I started messing around with the Python scripts (but I thought I restored the backups to submit a "clean" bug report). I'll double-check this.

**Comment by lonico** [comment] 2020-12-17 05:27
Closing as we could not reproduce it.
Let us know if you see it again.

**Closed by lonico** 2020-12-17 05:27 UTC
Labels: ElementSW, question
